### ISSUE TITLE
Add the ability to specify an id generation function

### ISSUE THREAD

**Issue by Morgul** [Morgul/jbase#8]
While `node uuid` is great in that it creates fast unique ids, it's not the most elegant thing to, say, put in a url. It would be great to allow people to specify their own ID generation function.

**Proposed api**

_Database API_:
```javascript
var db = jbase.db('some_db', {
    idFunc: function()
    {
        return Date.now();
    }
});
```

_Model API_:
```javascript
var Session = jbase.defineModel('sessions', {
    userID: { type: String, required: true }
}, {
    idFunc: function()
    {
        return Date.now();
    }
});
```

**Comment by Burstaholic** [comment]
Note: the whole ID system needs to be explained in the documentation.

**Comment by Morgul** [comment]
Agreed. I think the documentation needs an overhaul. I'd love some suggestions on how best to handle the documentation... autogenerated, some how?Use Github's wiki? Just markdown files in the repo?
